# Generated by Django 5.2.5 on 2025-12-02 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('DRIVER', 'Driver'), ('HIGHLIGHTS', 'Highlights'), ('VIDEO', 'Video'), ('DEBRIEF', 'Friday Debrief')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='articles/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
