# Generated by Django 5.2.5 on 2025-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date_range', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='races/')),
            ],
        ),
    ]
