# Generated by Django 5.2.5 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0004_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix', models.CharField(max_length=100)),
                ('country_flag', models.ImageField(upload_to='flags/')),
                ('date', models.DateField()),
                ('winner', models.CharField(max_length=100)),
                ('winner_img', models.ImageField(upload_to='drivers/')),
                ('team', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='teams/')),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
