# Generated by Django 5.2.5 on 2025-12-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0005_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='races/videos/'),
        ),
    ]
