# Generated by Django 5.2.5 on 2025-12-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0006_race_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='video',
        ),
    ]
