# Generated by Django 5.2.5 on 2025-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0007_remove_race_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='articles/videos/'),
        ),
    ]
