# Generated by Django 5.2.5 on 2025-12-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1app', '0009_passwordresetotp_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1app.usertable'),
        ),
    ]
